name: Animação da Cobrinha

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: oliveir4-vitor
          outputs: |
            dist/snake.svg?palette=github-dark

      - name: Publicar snake.svg no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
